### ISSUE TITLE
Forge 43.2.0 on very modded minecraft

### ISSUE THREAD

**Issue by SammyLikesLegos** [FoundationGames/Automobility#29]
No idea what's going on, mod was running fine before even with all of the mods. I also just downloaded create and flywheel so that could be the reason why. I updated some mods to new versions and this could possibly be the reason.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-01-13 15:17:10
Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class io.github.foundationgames.automobility.block.model.SlopeUnbakedModel
	at net.minecraft.client.resources.model.ModelBakery.handler$bal000$automobility$addUnbakedSlopeModels(ModelBakery.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23115!/:?] {re:mixin}
	at net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.resources.model.ModelBakery.handler$bal000$automobility$addUnbakedSlopeModels(ModelBakery.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23329!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, NoCaveAmbience+1.19.zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.handler$bal000$automobility$addUnbakedSlopeModels(ModelBakery.java:640)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.lang.RuntimeException: Automobility's load order was disrupted!
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.platform.Platform.get(Platform.java:54)
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.Automobility.<clinit>(Automobility.java:28)
	... 20 more

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 388903896 bytes (370 MiB) / 1006632960 bytes (960 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 5300G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=31.0.12016.4002
	Graphics card #1 name: AMD Radeon RX 5500
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4080.00
	Graphics card #1 deviceId: 0x7340
	Graphics card #1 versionInfo: DriverVersion=31.0.12016.4002
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26975.53
	Virtual memory used (MB): 15904.57
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 51.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.2-forge-43.2.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 5500 GL version 3.2.0 Core Profile Context 22.20.16.04.220811, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 3 5300G with Radeon Graphics 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by zaeonNineZero** [comment]
I've repeatedly encountered the same error, and I've noticed it only happens when another mod fails to meet its dependencies. Normally Forge will partially load the game to an error screen explaining the error, but with Automobility installed it straight-up crashes before ever reaching this screen.

A snippet of the associated log file when this crash occurs:
```
[15Jan2023 16:34:58.786] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File ShoulderSurfing-Forge-1.19.3-2.2.19.jar needs language provider javafml:44 or above to load
§7We have found 43

...

[15Jan2023 16:35:00.315] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27) ~[automobility-0.4.1+1.19.2-forge.jar%23376!/:?]
	at net.minecraft.client.resources.model.ModelBakery.handler$cng000$automobility$addUnbakedSlopeModels(ModelBakery.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23115!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23115!/:?]
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
Caused by: java.lang.RuntimeException: Automobility's load order was disrupted!
	at io.github.foundationgames.automobility.platform.Platform.get(Platform.java:54) ~[automobility-0.4.1+1.19.2-forge.jar%23376!/:?]
	at io.github.foundationgames.automobility.Automobility.<clinit>(Automobility.java:28) ~[automobility-0.4.1+1.19.2-forge.jar%23376!/:?]
	at io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27) ~[automobility-0.4.1+1.19.2-forge.jar%23376!/:?]
	at net.minecraft.client.resources.model.ModelBakery.handler$cng000$automobility$addUnbakedSlopeModels(ModelBakery.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23115!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23115!/:?]
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23575!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
```
So essentially when a mod fails to meet its dependencies, it screws with the game's load order, which screws up Automobility and causes it to straight up crash.

**Comment by SammyLikesLegos** [comment]
okay thanks, so that means I just remove from my mod list?

**Comment by zaeonNineZero** [comment]
Yes, then see which mod is missing its dependencies. Install the required dependency mods, test if the game successfully launches, then re-add automobility and see what happens.

**Comment by SammyLikesLegos** [comment]
Deleted Automobility and apparently I accidentally downloaded the 1.19.3 version of journeymap instead of the 1.19.2 version.
Though after I fixed it, it showed that my game crashed because of Exit Code -1073740940 and searching it up yields nothing.

**Comment by SammyLikesLegos** [comment]
![image](https://user-images.githubusercontent.com/122060485/213959425-dc0c8f8a-31a8-46b8-b77e-684675b6a8f0.png)

**Comment by SammyLikesLegos** [comment]
Pressed J to view JourneyMap and it crashed me, maybe that's the reason why
