### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by kaairu** [FoundationGames/Automobility#36]
crash while loading in mojang loading screen          FORGE 1.19.2

Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class io.github.foundationgames.automobility.block.model.SlopeUnbakedModel
	at net.minecraft.client.resources.model.ModelBakery.handler$ekm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23115!/:?] {re:mixin}
	at net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.accessor.AccessorModelManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,re:classloading,pl:mixin:APP:moonlight.mixins.json:ConditionsHackMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.resources.model.ModelBakery.handler$ekm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinModelBakery,pl:mixin:APP:mixins.hammerlib.json:client.ModelBakeryMixin,pl:mixin:APP:lightspeed.mixins.json:model.ModelBakeryMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:rubidium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin,pl:mixin:APP:tempad.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer,pl:mixin:APP:mixins.essential.json:client.renderer.MixinEntityRenderer_Zoom,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:json-entity-models.mixins.json:MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:mutantmore.mixins.json:MinecraftMixin,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:json-entity-models.mixins.json:MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23757!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Dungeons-Textures-0.2.3.zip, Brewing Guide.zip, EclecticTrove-noconfig-1.19-1.2.0.zip, JEMs Base Resources-0.1.0.zip, Repurposed_Structures-Better_Desert_Temples_v6.zip, mutantmore-barebones-1.19.2-1.0.zip, squishys reanimated.zip, eatinganimations+ 1.10.zip, SpawnEgg3D-23w07a.zip, Soft-Weather-1.0-1.19.zip, Repurposed_Structures-VillagersPlus_v1.zip, Repurposed_Structures-Savage_And_Ravage_v5.zip, Repurposed_Structures-Better_Dungeons_v4.zip, Repurposed_Structures-Better_Monuments_v5-With_Original_Monuments.zip, Repurposed_Structures-Better_Strongholds_v4.zip, Repurposed_Structures-Chef's_Delight_v1.zip, Repurposed_Structures-More_Villagers_v8.zip, Repurposed_Structures-Better_Nether_Fortress_v2.zip, Essential (forge_1.19.2).jar
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.handler$ekm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.lang.RuntimeException: Automobility's load order was disrupted!
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.platform.Platform.get(Platform.java:54)
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.Automobility.<clinit>(Automobility.java:28)
	... 20 more

**Comment by tenzedkariyu19** [comment]
didnt have moonlight installed :P
