### ISSUE TITLE
Automobility has conflicts with FTB Essentials on 1.19.2 Forge

### ISSUE THREAD

**Issue by AKAazure** [FoundationGames/Automobility#50]
During my testing, I have found both two automobility versions on 1.19.2 has conflicts with FTB Essentials.

Here is the the error log. Since FTB Essentials involves "tpa"-like commands, perhaps the conflicts is underlying in the teleporting functions as Automobility may consider a slope as a valid position?

```
[17:25:46] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
	at io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27) ~[automobility-0.4.1+1.19.2-forge.jar%23154!/:?]
	at net.minecraft.client.resources.model.ModelBakery.handler$zec000$automobility$addUnbakedSlopeModels(ModelBakery.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:386) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:611) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.lambda$new$6(ModelBakery.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23119!/:?]
	at net.minecraft.client.resources.model.ModelBakery.lambda$new$7(ModelBakery.java:194) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23119!/:?]
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:192) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
Caused by: java.lang.RuntimeException: Automobility's load order was disrupted!
	at io.github.foundationgames.automobility.platform.Platform.get(Platform.java:54) ~[automobility-0.4.1+1.19.2-forge.jar%23154!/:?]
	at io.github.foundationgames.automobility.Automobility.<clinit>(Automobility.java:28) ~[automobility-0.4.1+1.19.2-forge.jar%23154!/:?]
	at io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27) ~[automobility-0.4.1+1.19.2-forge.jar%23154!/:?]
	at net.minecraft.client.resources.model.ModelBakery.handler$zec000$automobility$addUnbakedSlopeModels(ModelBakery.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:386) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:611) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelBakery.lambda$new$6(ModelBakery.java:195) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23119!/:?]
	at net.minecraft.client.resources.model.ModelBakery.lambda$new$7(ModelBakery.java:194) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23119!/:?]
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:192) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[17:25:46] [Render thread/INFO]: Reloading ResourceManager: Default
[17:25:46] [Worker-Main-14/WARN]: Invalid sounds.json in resourcepack: 'Default'
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at net.minecraft.server.packs.FilePackResources.m_6105_(FilePackResources.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.AbstractPackResources.m_7211_(AbstractPackResources.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.resources.FallbackResourceManager.m_213713_(FallbackResourceManager.java:74) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.m_213713_(MultiPackResourceManager.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.sounds.SoundManager.m_120395_(SoundManager.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.sounds.SoundManager$Preparations.m_120425_(SoundManager.java:139) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:71) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.client.sounds.SoundManager.m_5944_(SoundManager.java:38) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23200!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by FoundationGames** [comment]
Automobility is known to cause a crash on Forge when other mods have missing dependencies. Please remove Automobility and check if any dependencies are required - if not, this issue will be left open
