### ISSUE TITLE
The game crashed whilst rendering overlay Error

### ISSUE THREAD

**Issue by Ctakep** [FoundationGames/Automobility#57]
So everything worked fine but one of my mods crashed (obscure api) so i got rid of it and from now on my game keeps crashing bc of multiple mods and now its time for automobility heres the crash: 

The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class io.github.foundationgames.automobility.block.model.SlopeUnbakedModel

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-05-21 21:38:28
Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class io.github.foundationgames.automobility.block.model.SlopeUnbakedModel
	at net.minecraft.client.resources.model.ModelBakery.handler$dlm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?] {re:mixin}
	at net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%23121!/:?] {}
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,re:classloading,pl:mixin:APP:moonlight.mixins.json:ConditionsHackMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.resources.model.ModelBakery.handler$dlm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:physicsmod.mixins.json:MixinModelBakery,pl:mixin:APP:connectedness.mixins.json:ModelLoaderAccessor,pl:mixin:APP:connectedness.mixins.json:ModelLoaderMixin,pl:mixin:APP:automobility_forge.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin,pl:mixin:APP:do-a-barrel-roll.mixins.json:GameRendererMixin,pl:mixin:APP:fairylights.mixins.json:GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:mixins.cobblemon-common.json:GameRendererMixin,pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin,pl:mixin:APP:physicsmod.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.satin.client.json:event.GameRendererMixin,pl:mixin:APP:immersive_aircraft.mixins.json:GameRendererMixin,pl:mixin:APP:beyond_earth.mixin.json:RenderBobView,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.blur.json:MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.satin.client.json:event.MinecraftClientMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.blur.json:MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:dungeons_libraries.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:physicsmod.mixins.json:MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:cloth.MixinMinecraft,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinMinecraft,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.satin.client.json:event.MinecraftClientMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23643!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.10.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, The-Great-Shrimpsby_v0.1.1.zip, Vanilla Advancement.zip, Visual Titles.zip, [1.2] Enhanced Boss Bars.zip, FeywildReduxV1.3.1.zip, Fantasy_Ores_Modded_v2_shiny_ores.zip, Pixelated_v1.3.1_EnhancedVisuals(nox_cgt).zip, FreshAnimations_v1.8.zip, Better Zombies.zip, Better Skeletons.zip, Better Zombies FA.zip, Better Skeletons FA.zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.block.model.SlopeUnbakedModel.<clinit>(SlopeUnbakedModel.java:27)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.handler$dlm000$automobility$addUnbakedSlopeModels(ModelBakery.java:2140)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:312)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:474)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_174903_(ModelBakery.java:170)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.m_119346_(ModelBakery.java:169)
	at MC-BOOTSTRAP/com.google.common@31.0.1-jre/com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:168)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:58)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.lang.RuntimeException: Automobility's load order was disrupted!
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.platform.Platform.get(Platform.java:54)
	at TRANSFORMER/automobility@0.4.1+1.19.2-forge/io.github.foundationgames.automobility.Automobility.<clinit>(Automobility.java:28)
	... 20 more

**Comment by Bammcool2011** [comment]
I have this issue too. When I updated Create mod to version 0.5.1.a

**Comment by NathanCPlaster** [comment]
I also keep having this issue

**Comment by zaeonNineZero** [comment]
This appears to be identical to #28 and #29, and several other issue reports as well. All are caused by Automobilty not playing nicely with the Forge mod dependency "crash" screen, as it causes all resource packs to unload themselves. This screws up something with Automobility's slopes and makes the whole game crash.

Hopefully when this mod is finally being updated again this issue will be taken care of.
