### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by DarkLinkMT** [FoundationGames/Automobility#85]
I have an error that does not start my server with this mod, when I try to open it I get 
"Caused by: java.lang.NoSuchFieldError: Class io.github.foundationgames.automobility.item.AutomobilityItems does not have member field 'java.util.Map frameModelPool'.
	at io.github.foundationgames.automobility.item.AutomobilityItems.<clinit>(AutomobilityItems.java:72) ~[automobility-0.3+1.18.2.2.jar:?]
	at io.github.foundationgames.automobility.Automobility.onInitialize(Automobility.java:45) ~[automobility-0.3+1.18.2.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.10.jar:?]
	... 6 more" 
Can you help me?
The log is this
[latest.log](https://github.com/FoundationGames/Automobility/files/14981386/latest.log)

**Comment by nicholasgrose** [comment]
1.18.2 is no longer being maintained:
![image](https://github.com/FoundationGames/Automobility/assets/35816886/c577f4d9-18b2-4f54-abba-ce1d3be07dc6)

However, I managed to hunt down and fix this bug with the following source code changes and a recompile:
![image](https://github.com/FoundationGames/Automobility/assets/35816886/0199f29a-2e1a-41f7-b433-4bf5188b1cbc)

It seems odd that the server should require those HashMaps to exist, though. They are only used in client code, so I'm unsure if this is the best possible fix. Either way it is functional.
